version: '2.0'

#volumes:
#  keycloak_postgres_data:
#      driver: local
#  keycloak_jboss_data:

services:
  postgres:
    image: postgres
    volumes:
      - ./keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    #ports:
      # - 54320:5432
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak_jboss_data:/opt
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 10090:8080
    depends_on:
      - postgres



